export default {
  PASSGENER_BOOKING_INIT: 0,
  PASSGENER_BOOKING_PICKED_ADDRESS: 1,
  PASSGENER_BOOKING_PICKED_OPTIONS: 2,
  PASSGENER_BOOKING_WAIT_SERVER_RESPONSE: 3,
  PASSGENER_BOOKING_WAIT_DRIVER_ACCEPT: 4,
  PASSGENER_BOOKING_WAIT_DRIVER_ON_THE_WAY: 5,
  PASSGENER_BOOKING_WAIT_DRIVER_ARRIVED: 6,
  PASSGENER_BOOKING_WAIT_ON_BOARD: 7,
  PASSGENER_BOOKING_ON_RATING: 8,
  PASSGENER_BOOKING_HAVE_COMPLETE: 9
}