source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
target 'dacsee' do
    
    pod 'AMapNavi'
    pod 'AMapSearch'
    pod 'AMapLocation'
    
    pod 'Bugly'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'


  pod 'rn-splash-screen', :path => '../node_modules/rn-splash-screen'

end
