export default {
  DRIVER_ON_WORK_INIT: 0,
  DRIVER_RECEVICE_JOBS: 1,
  DRIVER_ACCETP_JOBS: 2,
  DRIVER_ON_THE_WAY: 3,
  DRIVER_ARRIVED: 4,
  DRIVER_ON_BOARD: 5,
  DRIVER_ON_RATING: 6,
  DRIVER_HAVE_COMPLETE: 7,
  DRIVER_REJECT_JOBS: 10
}